name: 'run-action'
on: # rebuild any PRs and main branch changes
  pull_request:
    types:
      - opened
      - reopened

jobs:
  local-action: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn all
      - uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  marketplace-action:
    runs-on: ubuntu-latest
    steps:
    - name: another-pull-request-labeler
      uses: gplassard/pull-request-labeler@latest
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
